name: Quality Workflow

on:
  push:
    branches:
      - feature/*
      - feat/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install from package lock
        run: |
          npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Prepare Files for Deployment
        run: npm run build-prod
